spring:
  datasource:
    url: ${MESSENGER_AUTH_SERVICE_DATABASE_URL}
    username: ${MESSENGER_AUTH_SERVICE_DATABASE_USER}
    password: ${MESSENGER_AUTH_SERVICE_DATABASE_PASSWORD}

app:
  jwt:
    private-key: ${MESSENGER_AUTH_SERVICE_ACCESS_TOKEN_PRIVATE_KEY}
